-- Users table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  user_id text unique not null, -- 16-digit ID
  public_key text not null,
  private_key text not null, -- stored encrypted at rest in Supabase (assume RLS + encryption)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Friends table
create table if not exists public.friends (
  id bigint generated by default as identity primary key,
  from_user_id text not null,
  to_user_id text not null,
  status text not null check (status in ('pending','accepted','declined')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_friends_users on public.friends (from_user_id, to_user_id);

-- Messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  from_user_id text not null,
  to_user_id text not null,
  encrypted_content jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_messages_users on public.messages (from_user_id, to_user_id, created_at);

-- RLS policies (simplified)
alter table public.users enable row level security;
alter table public.friends enable row level security;
alter table public.messages enable row level security;

-- Simple permissive policies for development
create policy if not exists "read all dev" on public.users for select using (true);
create policy if not exists "insert dev" on public.users for insert with check (true);

create policy if not exists "read all friends" on public.friends for select using (true);
create policy if not exists "insert friends" on public.friends for insert with check (true);
create policy if not exists "update friends" on public.friends for update using (true);

create policy if not exists "read msgs" on public.messages for select using (true);
create policy if not exists "insert msgs" on public.messages for insert with check (true);

-- Signup users table
create table if not exists public.signup_users (
  id serial primary key,
  full_name text not null,
  email text not null unique,
  phone_number text not null,
  created_at timestamptz default now()
);

-- OTP verifications table
create table if not exists public.otp_verifications (
  id serial primary key,
  phone_number text not null,
  otp text not null,
  is_verified boolean default false,
  created_at timestamptz default now(),
  expires_at timestamptz
);

-- RLS policies for new tables
alter table public.signup_users enable row level security;
alter table public.otp_verifications enable row level security;

create policy if not exists "read all signup_users" on public.signup_users for select using (true);
create policy if not exists "insert signup_users" on public.signup_users for insert with check (true);

create policy if not exists "read all otp_verifications" on public.otp_verifications for select using (true);
create policy if not exists "insert otp_verifications" on public.otp_verifications for insert with check (true);
create policy if not exists "update otp_verifications" on public.otp_verifications for update using (true);