// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/types';

const SUPABASE_URL = "https://tljsyavtwbvwkteckiud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsanN5YXZ0d2J2d2t0ZWNraXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDQ4ODYsImV4cCI6MjA3MTI4MDg4Nn0.IxBVfj1XzPXS6zbwbBuVyu90uaHORXw2KahI1Qn4uDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);